/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AnalysisInput = IDL.Record({
  'vix' : IDL.Float64,
  'volatilePercentage' : IDL.Float64,
  'downsidePercentage' : IDL.Float64,
  'weeklyStopLoss' : IDL.Float64,
  'monthlyStopLoss' : IDL.Float64,
  'spot' : IDL.Float64,
  'upsidePercentage' : IDL.Float64,
  'monthlyTarget' : IDL.Float64,
  'weeklyTarget' : IDL.Float64,
});
export const Time = IDL.Int;
export const Analysis = IDL.Record({
  'vix' : IDL.Float64,
  'volatilePercentage' : IDL.Float64,
  'downsidePercentage' : IDL.Float64,
  'weeklyStopLoss' : IDL.Float64,
  'monthlyStopLoss' : IDL.Float64,
  'spot' : IDL.Float64,
  'timestamp' : Time,
  'upsidePercentage' : IDL.Float64,
  'monthlyTarget' : IDL.Float64,
  'weeklyTarget' : IDL.Float64,
});
export const Preferences = IDL.Record({
  'vix' : IDL.Float64,
  'expiryDates' : IDL.Vec(IDL.Text),
  'strike' : IDL.Float64,
  'premium' : IDL.Float64,
  'resistanceLevel' : IDL.Float64,
  'spotPrice' : IDL.Float64,
  'supportLevel' : IDL.Float64,
  'optionType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnalysis' : IDL.Func([AnalysisInput], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(Analysis)], ['query']),
  'getPreferences' : IDL.Func([], [Preferences], ['query']),
  'storePreferences' : IDL.Func([Preferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AnalysisInput = IDL.Record({
    'vix' : IDL.Float64,
    'volatilePercentage' : IDL.Float64,
    'downsidePercentage' : IDL.Float64,
    'weeklyStopLoss' : IDL.Float64,
    'monthlyStopLoss' : IDL.Float64,
    'spot' : IDL.Float64,
    'upsidePercentage' : IDL.Float64,
    'monthlyTarget' : IDL.Float64,
    'weeklyTarget' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Analysis = IDL.Record({
    'vix' : IDL.Float64,
    'volatilePercentage' : IDL.Float64,
    'downsidePercentage' : IDL.Float64,
    'weeklyStopLoss' : IDL.Float64,
    'monthlyStopLoss' : IDL.Float64,
    'spot' : IDL.Float64,
    'timestamp' : Time,
    'upsidePercentage' : IDL.Float64,
    'monthlyTarget' : IDL.Float64,
    'weeklyTarget' : IDL.Float64,
  });
  const Preferences = IDL.Record({
    'vix' : IDL.Float64,
    'expiryDates' : IDL.Vec(IDL.Text),
    'strike' : IDL.Float64,
    'premium' : IDL.Float64,
    'resistanceLevel' : IDL.Float64,
    'spotPrice' : IDL.Float64,
    'supportLevel' : IDL.Float64,
    'optionType' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnalysis' : IDL.Func([AnalysisInput], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(Analysis)], ['query']),
    'getPreferences' : IDL.Func([], [Preferences], ['query']),
    'storePreferences' : IDL.Func([Preferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };