/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Analysis {
  'vix' : number,
  'volatilePercentage' : number,
  'downsidePercentage' : number,
  'weeklyStopLoss' : number,
  'monthlyStopLoss' : number,
  'spot' : number,
  'timestamp' : Time,
  'upsidePercentage' : number,
  'monthlyTarget' : number,
  'weeklyTarget' : number,
}
export interface AnalysisInput {
  'vix' : number,
  'volatilePercentage' : number,
  'downsidePercentage' : number,
  'weeklyStopLoss' : number,
  'monthlyStopLoss' : number,
  'spot' : number,
  'upsidePercentage' : number,
  'monthlyTarget' : number,
  'weeklyTarget' : number,
}
export interface Preferences {
  'vix' : number,
  'expiryDates' : Array<string>,
  'strike' : number,
  'premium' : number,
  'resistanceLevel' : number,
  'spotPrice' : number,
  'supportLevel' : number,
  'optionType' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAnalysis' : ActorMethod<[AnalysisInput], undefined>,
  'clearHistory' : ActorMethod<[], undefined>,
  'getAnalysisHistory' : ActorMethod<[], Array<Analysis>>,
  'getPreferences' : ActorMethod<[], Preferences>,
  'storePreferences' : ActorMethod<[Preferences], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];